<?php
// +----------------------------------------------------------------------
// | Copyright (c) 2015-2016 http://www.ebpays.com All rights reserved.
// +----------------------------------------------------------------------
// | Author: xiaofeng<1034023036@qq.com>
// +----------------------------------------------------------------------

return array(
    'bank' => array(
        'gonghang' => '工商银行',
        'jianhang' => '建设银行',
        'nonghang' => '农业银行',
        'zhaohang' => '招商银行',
        'zhonghang' => '中国银行',
        'pufa' => '浦发银行',
        'jiaohang' => '交通银行',
        'minsheng' => '民生银行',
        'xingye' => '兴业银行',
        'guangda' => '光大银行',
        'guangfa' => '广发银行',
        'zhongxin' => '中信银行',
        'chuxu' => '邮政储蓄',
        'shenfa' => '平安银行',
        'beijing' => '北京银行',
        'shanghai' => '上海银行',
        'bjnongshang' => '北京农商银行',
        'huaxia' => '华夏银行',
        'nanjing' => '南京银行',
        'bohai' => '渤海银行',
        'hangzhou' => '杭州银行',
        'shnongshang' => '上海农村商业银行',
        'zheshang' => '浙商银行',
        'ningbo' => '宁波银行',
        'weixin' => '微信',
        'alipay' => '支付宝',
        'jd' => '京东',
        'baidu' => '百度',
        'qita' => '其他银行',
    ),
    'bankcode' => array(
        '工商银行' => 'gonghang',
        '建设银行' => 'jianhang',
        '农业银行' => 'nonghang',
        '招商银行' => 'zhaohang',
        '中国银行' => 'zhonghang',
        '浦发银行' => 'pufa',
        '交通银行' => 'jiaohang',
        '民生银行' => 'minsheng',
        '兴业银行' => 'xingye',
        '光大银行' => 'guangda',
        '宁波银行' => 'ningbo',
        '广发银行' => 'guangfa',
        '中信银行' => 'zhongxin',
        '邮政储蓄' => 'chuxu',
        '平安银行' => 'shenfa',
        '北京银行' => 'beijing',
        '上海银行' => 'shanghai',
        '北京农商银行' => 'bjnongshang',
        '华夏银行' => 'huaxia',
        '南京银行' => 'nanjing',
        '渤海银行' => 'bohai',
        '杭州银行' => 'hangzhou',
        '上海农村商业银行' => 'shnongshang',
        '浙商银行' => 'zheshang',
        '微信' => 'weixin',
        '支付宝' => 'alipay',
        '京东' => 'jd',
        '百度' => 'baidu',
        '其他银行' => 'qita',
    )
);